CC := gcc

CFLAGS := -Wall -DDEBUG

all: first second third fourth fifth

first:
	$(CC) -o first first.c
second:
	$(CC) -o second second.c
third:
	$(CC) -o third third.c
fourth:
	$(CC) -o fourth fourth.c
fifth:
	$(CC) -o fifth fifth.c

clean:
	rm -f first second third fourth fifth
